"""
Populates the demo gallery (frontend/public/example-images/ + the manifest
at frontend/src/data/exampleImages.js) with real GAMUS VALIDATION samples --
never used in training -- streamed fresh from HuggingFace, no local disk
cache needed beforehand (same streaming approach used throughout this
project, e.g. gamus_loader.py).

Buckets samples by land-cover mask composition so the gallery has a mix,
not two dozen near-duplicate dense-downtown crops:
  - building_heavy : >35% building pixels
  - vegetation_heavy: >35% combined tree + low_vegetation pixels
  - water          : >20% water pixels (rarer class, worth its own bucket
                     given the wetland-tile weakness already known from
                     segmentation eval -- good to show it honestly, not hide it)
  - mixed          : everything else (typical suburban/general scenes)

Run from backend/ (needs the same HF network access gamus_loader.py already
uses):
    python scripts/generate_example_gallery.py --per-bucket 6

Takes a couple minutes (HF streaming + PNG encoding), not instant.
"""
import argparse
import json
import os
import sys

import numpy as np
from PIL import Image

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from app.data import gamus_loader  # noqa: E402

REPO_ROOT = os.path.join(os.path.dirname(__file__), "..", "..")
GALLERY_DIR = os.path.join(REPO_ROOT, "frontend", "public", "example-images")
MANIFEST_PATH = os.path.join(REPO_ROOT, "frontend", "src", "data", "exampleImages.js")

BUILDING_ID = 3
WATER_ID = 4
TREE_ID = 6
LOW_VEG_ID = 2

BUCKET_LABELS = {
    "building_heavy": "Dense urban / buildings",
    "vegetation_heavy": "Vegetation-heavy terrain",
    "water": "Water / coastal",
    "mixed": "Mixed / general terrain",
}


def classify_bucket(landcover_mask: np.ndarray) -> str:
    total = landcover_mask.size
    building_frac = np.sum(landcover_mask == BUILDING_ID) / total
    veg_frac = np.sum((landcover_mask == TREE_ID) | (landcover_mask == LOW_VEG_ID)) / total
    water_frac = np.sum(landcover_mask == WATER_ID) / total

    if building_frac > 0.35:
        return "building_heavy"
    if veg_frac > 0.35:
        return "vegetation_heavy"
    if water_frac > 0.20:
        return "water"
    return "mixed"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--per-bucket", type=int, default=6,
                         help="How many images to collect per bucket (default 6, so ~24 total).")
    parser.add_argument("--max-samples", type=int, default=2000,
                         help="Safety cap on how many streamed samples to scan before giving up.")
    args = parser.parse_args()

    os.makedirs(GALLERY_DIR, exist_ok=True)

    buckets = {name: [] for name in BUCKET_LABELS}
    manifest_entries = []

    print("Streaming GAMUS validation split (never trained on)...")
    stream = gamus_loader.load_gamus_split(split="val", streaming=True)

    scanned = 0
    for sample in stream:
        scanned += 1
        if scanned > args.max_samples:
            print(f"Hit --max-samples ({args.max_samples}) before filling every bucket. "
                  f"Current counts: { {k: len(v) for k, v in buckets.items()} }")
            break

        if all(len(v) >= args.per_bucket for v in buckets.values()):
            break

        try:
            rgb = gamus_loader.get_rgb_image(sample)
            landcover = gamus_loader.get_landcover_mask(sample)
        except KeyError as exc:
            print(f"Skipping sample {scanned}: {exc}")
            continue

        bucket = classify_bucket(landcover)
        if len(buckets[bucket]) >= args.per_bucket:
            continue

        idx = len(buckets[bucket])
        filename = f"gamus_val_{bucket}_{idx:02d}.png"
        out_path = os.path.join(GALLERY_DIR, filename)

        Image.fromarray(rgb.astype(np.uint8)).save(out_path, format="PNG")
        buckets[bucket].append(filename)

        manifest_entries.append({
            "id": f"gamus-{bucket}-{idx:02d}",
            "filename": filename,
            "type": "png",
            "label": f"{BUCKET_LABELS[bucket]} #{idx + 1}",
            "source": "GAMUS (held-out validation split)",
            "description": "Never used in training -- validation split only.",
            "georeferenced": False,
        })

        print(f"  saved {filename}  ({bucket}, {len(buckets[bucket])}/{args.per_bucket})")

    if scanned <= args.max_samples:
        print(f"Filled every bucket after scanning {scanned} samples.")

    # Write the manifest as real JS (matches exampleImages.js's existing format)
    js_entries = ",\n".join(
        "  " + json.dumps(entry, indent=2).replace("\n", "\n  ") for entry in manifest_entries
    )
    manifest_js = f"""/**
 * Auto-generated by scripts/generate_example_gallery.py -- real GAMUS
 * validation-split samples (never trained on), bucketed by land-cover
 * composition. Re-run that script to regenerate with a different mix.
 */
const exampleImages = [
{js_entries}
];

export default exampleImages;
"""
    with open(MANIFEST_PATH, "w") as f:
        f.write(manifest_js)

    print(f"\nWrote {len(manifest_entries)} entries to {MANIFEST_PATH}")
    print(f"Images saved to {GALLERY_DIR}")
    print("Bucket counts:", {k: len(v) for k, v in buckets.items()})


if __name__ == "__main__":
    main()
